/* Copyright (C) Kais Dukes, 2009.
 * 
 * This file is part of JQuranTree.
 * 
 * JQuranTree is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * JQuranTree is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with JQuranTree. If not, see <http://www.gnu.org/licenses/>.
 */

package org.jqurantree.core.error;

/**
 * Utility class which contains the list of error messages generated by the API
 * when throwing exceptions.
 * 
 * @author Kais Dukes
 */
public class Errors {

	static {

		// Code coverage.
		new Errors();
	}

	private Errors() {
	}

	/**
	 * Gets the total number of error messages.
	 * 
	 * @return a positive integer
	 */
	public static int getErrorCount() {
		return 10;
	}

	/**
	 * {@value}
	 */
	public static final String INVALID_TANZIL_XML = "Failed to read Tanzil XML.";

	/**
	 * {@value}
	 */
	public static final String INVALID_CHAPTER_NUMBER = "Chapter numbers should be between 1 and 114 inclusive.";

	/**
	 * {@value}
	 */
	public static final String INVALID_VERSE_NUMBER = "The verse number is out of range.";

	/**
	 * {@value}
	 */
	public static final String IMMUTABLE_COLLECTION = "The collection is immutable and cannot be modified.";

	/**
	 * {@value}
	 */
	public static final String INVALID_ENCODING_TYPE = "The specified encoding type is not supported.";

	/**
	 * {@value}
	 */
	public static final String INVALID_COLUMN_NAME = "The specific column could not be found.";

	/**
	 * {@value}
	 */
	public static final String RESOURCE_NOT_FOUND = "The embedded JAR resource could not be found.";

	/**
	 * {@value}
	 */
	public static final String RESOURCE_CLOSE_FAILED = "Failed to close embedded JAR resource.";

	/**
	 * {@value}
	 */
	public static final String RESOURCE_READ_FAILED = "Failed to read embedded JAR resource.";

	/**
	 * {@value}
	 */
	public static final String FILE_NOT_FOUND = "The specified file could not be found.";
}
